### ISSUE TITLE
Should we change our main branch from 'master' to 'main'?

### ISSUE THREAD

**Issue by ricardozanini** [m88i/nexus-operator#106]
Looks like `master` is a racism term. I'd like to hear from you guys more about it:
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by LCaparelli** [comment]
While I agree that "master" is a racist term under the "master/slave" context, I don't think it is on other contexts (such as "dungeon master").

I see that article briefly mentions this and concludes that "Turns out the original usage of master in Git very likely came from another version control system (BitKeeper) that explicitly had a notion of slave branches". Right, but git _isn't_ BitKeeper and it _doesn't_ have the notion of slave branches. 

I see the [e-mail](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html) with the supporting reasoning, but it still seems like a bit of stretch to me. It defends that git used the same name BitKeeper does, but I'm not sure I see how that's undeniable evidence that "master" here is in the "master/slave" context nor that git was inspired by BitKeeper when naming this. 

In the end, I'm not part of the people who could be offended by this and my opinion should be weighed as such (i.e., not worth much). From a practical point of view, "main" still makes perfect sense and IMO it's even a better description of the branch as I find "master" to be pretty vague.

While I'm not fully onboard with the reasoning proposed by the article, I respect people's right to agree with that reasoning and to be offended by the term. IMO, changing it to "main" brings no negative effects and is a very nice step towards the sort of inclusive and respectful community we aim to be.

**Comment by ricardozanini** [comment]
I agree with your wall of text. =D

I'll rename the branch tonight. :)

**Comment by Kaitou786** [comment]
+1 for the change =D

**Comment by ricardozanini** [comment]
I forget to change, will do in the weekend

**Comment by LCaparelli** [comment]
@ricardozanini @Kaitou786 the article got updated:

> UPDATE: There is Good analysis of the whole main branch convo in the Git Rev News: Edition 65. Git likely uses master in the context of "master copy" or "master recording."

So that argument that seemed like a bit of was stretch was probably a stretch. In any case I still believe only good will come from this change and we should move forward with it.

**Comment by ricardozanini** [comment]
+1
I need to update this as soon as I have the time. At least for 0.3.0.

**Comment by ricardozanini** [comment]
PR merged, now we need to get rid of master post 0.3 release.
