### ISSUE TITLE
Rolling update cannot continue due to  Multi-Attach error

### ISSUE THREAD

**Issue by lexxy23** [m88i/nexus-operator#203]
**Describe the bug**
I am using the nexus operator, and I want to use the auto update mechanism of it. However, when I enabled the auto update, it is failing due to:

Normal   Scheduled           <unknown>                                     Successfully assigned storage/nxs-5956679dff-s8m9z to hnode1         │
│   Warning  FailedAttachVolume  8m26s                attachdetach-controller  Multi-Attach error for volume "pvc-267f63a2-53f3-4647-aec8-527281b393c3" Volume is already used by pod(s) nxs-864dc474b5-rrk2m                                                                                        │
│   Warning  FailedMount         6m23s                kubelet, hnode1          Unable to attach or mount volumes: unmounted volumes=[nxs-data], unattached volumes=[nxs-token-qs5sv nxs-data]: timed out waiting for the condition                                                                   │
│   Warning  FailedMount         109s (x2 over 4m4s)  kubelet, hnode1          Unable to attach or mount volumes: unmounted volumes=[nxs-data], unattached volumes=[nxs-data nxs-token-qs5sv]: timed out waiting for the condition

**To Reproduce**
1. install the nexus operator
2. install an initial setup using version nexus 3.28.x
3. enable auto-update afterwards (should find nexus 3.29.y)

**Expected behavior**
It should perform an update :)

**Environment**
Kubernetes 1.19.3
StorageClass: longhorn

Versions:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
I think it is because the new nexus instance tries to also reuse the existing volume, but longhorn refuses to share it. I guess the PVC setting is ReadWriteOnce, and due to the RollingUpdate strategy the nx operator tries to create a new instance with the existing PV(C) and therefore fails.

So, this is a difficult question. Perhaps one can use the ReadWriteMany setting in PV(C), or the RollingUpdate strategy needs to be changed :/ any recommendations?

**Comment by LCaparelli** [comment]
Hi @lexxy23, thanks for reaching out!

This looks like the same scenario as #191, please consider having a look at that one if you can.

> I think it is because the new nexus instance tries to also reuse the existing volume, but longhorn refuses to share it. I guess the PVC setting is ReadWriteOnce, and due to the RollingUpdate strategy the nx operator tries to create a new instance with the existing PV(C) and therefore fails.
>
> So, this is a difficult question. Perhaps one can use the ReadWriteMany setting in PV(C), or the RollingUpdate strategy needs to be changed :/ any recommendations?

Using ReadWriteOnce would fix one of the problems here, but ultimately still wouldn't allow for a rolling update when persistence is enabled because the older Nexus server will still be holding a lock file in the mounted filesystem, preventing the newer Nexus from acquiring this lock and starting successfully.

Because of that, in 0.5.0 we changed the strategy from `RollingUpdate` to `Recreate`, effectively killing the previous deployment before starting the new one, thus preventing this form of deadlock. Unfortunately this leads to temporary unavailability of service while the new server spins up.

We're currently working to release 0.5.0 into OperatorHub so it can be installed via OLM, but you may still manually install this release following the method in our [Quick Start guide](https://github.com/m88i/nexus-operator#quick-install).

>    install an initial setup using version nexus 3.28.x
>    enable auto-update afterwards (should find nexus 3.29.y)

Please note that the automatic update feature is confined within the same minor ("y" in "x.y.z"), so the update would occur from 3.28.x to 3.28.y, not from 3.28.x to 3.29.y.

Please let us know if you have any questions and we'll be happy to help! :-)

**Comment by lexxy23** [comment]
Hi, Lucas,

sounds great 👍  I will check the manual installation.

Thank you.
