### ISSUE TITLE
Pods can't be started on OCP 3.x clusters with default configuration

### ISSUE THREAD

**Issue by LCaparelli** [m88i/nexus-operator#41]
When attempting to deploy to an OCP 3.x cluster the following error pops up:

~~~
Error creating: pods "nexus3-695b67564f-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{200}: 200 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 200: must be in the ranges: [1000160000, 1000169999]]
~~~

As Nexus must run using this UID the cluster administrator needs to create a scc to work around this. It would be nice if we could supply this scc and have this documented.

**Comment by ricardozanini** [comment]
The reason of this BUG is that OCP 3.11 has a default SCC that prevents userID with low numbers, such as 200 (the one Nexus uses). To fix this, a custom SCC must be created in the namespace. See: https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.html

We will document and add a SCC example to the project to help administrators have the operator working on OCP 3.11 clusters.

**Comment by ricardozanini** [comment]
Pushing to 0.2.0, if we have the time by the end of the milestone we should include this one.
