### ISSUE TITLE
Level up to "Seamless Upgrades" capability level

### ISSUE THREAD

**Issue by ricardozanini** [m88i/nexus-operator#62]
Issue to track our capability level. We should be able to do minor upgrades of the installed Nexus Server. This will probably impact the way we handle the application image, since we are using `latest` tag by default, which is not a good practice. Today, if the user provides an image for the Nexus server, the operator will stick with it, unless the user manually change it later in the CR.

Ideally, users should be able to define the major Nexus version and the operator should upgrade minor versions automatically. We will reach another maturity level with this approach. See: https://sdk.operatorframework.io/docs/operator-capabilities/#level-2---seamless-upgrades

**Comment by ricardozanini** [comment]
Related to #14

**Comment by LCaparelli** [comment]
### Proposal
#### Nexus updates
We support two platforms: Openshift and Kubernetes.

On Openshift, we can levarage ImageStreams (#14), but we don't have a similar abstraction mechanism on Kubernetes. This means that on Kubernetes  we'll need to interact solely with the registry that provides the images.

Speaking of images, supporting custom images can quickly complicate matters as we cannot rely on correct semantic versioning, meaning we can't determine whether or not the candidate image release breaks compatibility or not. Due to this I believe we should not perform automatic upgrades when a custom image is being used. This must be well documented to users so it's clear they need to perform additional, manual steps to update their deployment.

Regardless of the platform the first step is detecting whether or not an update is available. We can use [Heroku's registry client](https://github.com/heroku/docker-registry-client) (or [this fork from Nokia](https://github.com/nokia/docker-registry-client) that seems to handle some bugs -- if we run into any, that is). With it we can fetch a the list of tags for an image and determine whether or not an update is necessary.

This is tricky with Red Hat certified images, as it requires authentication to the registry. This part is still a bit muddy to me, but I believe we should be able to fetch the credentials from the user via the Secret API. Once we get past that, we should be ok. This is also necessary for pulling the target tag if an update should be performed.

With proper configuration of the Deployment, ImageStreams can [trigger a new deployment](https://docs.openshift.com/container-platform/4.5/openshift_images/image-streams-manage.html#images-using-imagestream-change-triggers_image-streams-managing) once the image reference gets updated.

On Kubernetes we only need to modify the Deployment to point to the newer image.

We also need a rollback mechanism if the deployment with the new version fails. The procedure should be analogous to updating, except it will use the previous image, which should be stored. This leads to a problem in case the Operator fails while performing a rollback, as the previous image will be lost and the Operator will not be aware of the previous state. If this happens, manual intervention from the user is required to inform a stable tag, which is far from ideal. I'm not sure if there is a better solution for this.

#### Operator Updates
Quay does not require auth, so it should be really simple to update the operator. Simply changing the Operator's deployment to point to the newer image should do the trick and Kubernetes will handle the rest.

#### Concerns
I'm mostly concerned with the scenario on which the Operator fails during a rollback. If this happens in the middle of the night it could be one big headache for the administrator. Not only manual intervention is required, but the user would also need to be aware of which image it should rollback to. Maybe the Operator could try downgrading the image to a working version automatically depending on the error (we wouldn't want this if there was a network failure, for example, preventing us from pulling the image -- we would want this if the image is pulled successfully but fails to deploy correctly)?

Another concern: do we really need ImageStreams for the Openshift scenario? Wouldn't it be simpler to deal with it the same way as Kubernetes (i.e., simply change the deployment image and let Kubernetes spawn another ReplicaSet to deal with it)? I think the benefits of using an ImageStream are not clear to me at the moment.

**Comment by ricardozanini** [comment]
> Operator Updates
For this one, we use OLM that can also be installed on Kubernetes. Serious operator users should be aware - and use it. I won't add this feature (upgrade the operator on non-OLM scenarios) now.

**Comment by ricardozanini** [comment]
> Another concern: do we really need ImageStreams for the Openshift scenario? Wouldn't it be simpler to deal with it the same way as Kubernetes (i.e., simply change the deployment image and let Kubernetes spawn another ReplicaSet to deal with it)? I think the benefits of using an ImageStream are not clear to me at the moment.

ImageStreams can have multiple tags and we should keep the last 5. If something goes wrong, we just point to a previous tag.
