### ISSUE TITLE
Integrate PR CI Check with Coveralls or Codecov

### ISSUE THREAD

**Issue by ricardozanini** [m88i/nexus-operator#89]
Add unit test coverage reports with Coveralls: https://github.com/marketplace/actions/coveralls-github-action

**Comment by ricardozanini** [comment]
Or: https://codecov.io

**Comment by Kaitou786** [comment]
I think codecov is better it gives us more flexibility.

**Comment by ricardozanini** [comment]
I believe we will have to figure out their check method. :(

Maybe opening an issue in their repo asking about it? Do we have resources/reproducer to show them?

**Comment by Kaitou786** [comment]
I checked the codecov report I think we can use it, all the parts showed covered in go tool is also covered in codecov(Which should be the case as it is using same report). The only difference which I found was the coverage shown on codecov is a bit more because it considers the line where the function is defined as covered whereas go tool ignores it(does not track that line). For eg. in file `pkg/controller/nexus/resource/deployment/deployment.go` 
![Codecov](https://user-images.githubusercontent.com/36669272/85728748-d5f4ae00-b715-11ea-9fe8-cc9fc7355e93.png)
![go tool](https://user-images.githubusercontent.com/36669272/85728764-d8ef9e80-b715-11ea-84b6-3f0185ee7deb.png)

**Comment by ricardozanini** [comment]
@Kaitou786 looks good to me. If you've already implemented, bring it on! Do you need any information from me or do you need that I adjust any setting in the repository itself?

**Comment by Kaitou786** [comment]
@ricardozanini yes, can you signup on codecov.io with github and add this `m88i/nexus-operator` repository over there? Currently the report that I sent was from my forked repo.

**Comment by LCaparelli** [comment]
Sounds good to me! On a sidenote, gotta love that html format from `go tool cover`. go.tooling++

**Comment by ricardozanini** [comment]
> @ricardozanini yes, can you signup on codecov.io with github and add this `m88i/nexus-operator` repository over there? Currently the report that I sent was from my forked repo.

Done! https://codecov.io/gh/m88i/nexus-operator

**Comment by Kaitou786** [comment]
Thanks!, I'll send the PR sometime tomorrow =D
